[package]
name = "portaudio-mojo"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[package.host-dependencies]
ffipointer = { path = "../ffipointer" }
